#!/bin/bash

WEBPAGE_DIR=/home/teddy/math/web/personal/weisman

EXCLUDE_MKVS="--exclude=*.mkv"
if [[ "$1" == "--mkv" ]]; then
    echo "Not excluding mkvs"
    EXCLUDE_MKVS=""
fi

rsync -r --copy-unsafe-links --delete $EXCLUDE_MKVS $WEBPAGE_DIR/public_html/ $UT_MATH:~/public_html
