#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
UMICH_SERVER=tjwei@sftp.itd.umich.edu

WEBPAGE_DIR=$SCRIPT_DIR/tjwei

EXCLUDE_MKVS="--exclude=*.mkv"
if [[ "$1" == "--mkv" ]]; then
    echo "Not excluding mkvs"
    EXCLUDE_MKVS=""
fi

rsync -r --copy-unsafe-links -F --delete-after --exclude=dixit $EXCLUDE_MKVS --dry-run --verbose $WEBPAGE_DIR/public_html/ $UMICH_SERVER:~/Public/html
